# currently this is used for development purposes
version: "3.8"

services:
  leader: 
    image: "ileader"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leader
    ports: 
      - "8000:8000"
    environment:
      CONFIG_INDEX: 0
      CONFIG_PATH: "./config.txt"
      BOOTSTRAPPING_TIME: ${BOOTSTRAPPING_TIME}
    networks:
      - default

  follower1:
    image: "ifollower1"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: follower1
    ports: 
      - "8001:8001"
    environment:
      CONFIG_INDEX: 1
      CONFIG_PATH: "./config.txt"
      BOOTSTRAPPING_TIME: ${BOOTSTRAPPING_TIME}
    networks:
      - default

  follower2:
    image: "ifollower2"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: follower2
    ports: 
      - "8002:8002"
    environment:
      CONFIG_INDEX: 2
      CONFIG_PATH: "./config.txt"
      BOOTSTRAPPING_TIME: ${BOOTSTRAPPING_TIME}
    networks:
      - default
      
  # follower3:
  #   image: "follower3"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: follower3
  #   ports: 
  #     - "8003:8003"
  #   environment:
  #     CONFIG_INDEX: 3
  #     CONFIG_PATH: "./config.txt"
  #     BOOTSTRAPPING_TIME: ${BOOTSTRAPPING_TIME}

  #   volumes:
  #     - /Users/ruslanakhtariev/github/dolev-strong:/protocol

networks:
  default:
    driver: bridge