[package]
name = "proto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "3.3.0"
protoc-rust = "2"

[dev-dependencies]
protobuf-codegen-pure = "2.28.0"
